const CONFIG={endpoint:'https://script.google.com/macros/s/AKfycbzsas2HkpF4G9IGP5y2biOwqfW4Quf5l0_Hh2U5d4D4SHr4aEW5prZJVN_trOqqtqOT/exec',formVersion:'2.0.0'};
const TEXT={
zh:{back:'← 选择语言',eyebrow:'您的旅程，我们用心',title:'中国之旅满意度调查',intro:'感谢您选择 Nimbus Travel。您的真实反馈将帮助我们持续提升在中国的旅行服务。',trip:'行程信息',tripHelp:'请填写您参加的团组和线路信息。',group:'团组编号',name:'姓名',cities:'游览城市',itinerary:'行程线路',spots:'主要景点',service:'服务评价',ratingHelp:'请选择一至五星，五星代表非常满意。',commentsTitle:'意见与建议',commentsHelp:'欢迎分享旅程亮点、建议或需要我们改进的地方。',consent:'我同意 Nimbus Travel 将本次反馈用于服务质量改进。',privacy:'反馈仅用于服务质量管理，请勿填写护照、银行卡或其他敏感信息。',submit:'提交评价',sending:'正在提交…',successTitle:'感谢您的反馈',successText:'您的评价已经成功提交。祝您旅途愉快，期待再次与您相见。',again:'再填写一份',required:'请填写此项',ratingRequired:'请选择评分',consentRequired:'请勾选同意',network:'提交失败，请检查网络后重试。',hotelBreakfast:'酒店早餐',hotelFacilities:'酒店设施',hotelService:'酒店服务',restaurantQuality:'餐厅菜品质量',restaurantService:'餐厅服务',guideAttitude:'导游服务态度',overall:'总体满意度'},
en:{back:'← Language',eyebrow:'YOUR JOURNEY, OUR CARE',title:'China Travel Satisfaction Survey',intro:'Thank you for travelling with Nimbus Travel. Your feedback helps us improve every journey in China.',trip:'Trip information',tripHelp:'Please tell us which group and itinerary you joined.',group:'Group code',name:'Name',cities:'Cities visited',itinerary:'Itinerary',spots:'Main scenic spots',service:'Service rating',ratingHelp:'Choose one to five stars. Five means excellent.',commentsTitle:'Comments and suggestions',commentsHelp:'Share your highlights, suggestions or areas where we can improve.',consent:'I agree that Nimbus Travel may use this feedback to improve service quality.',privacy:'Feedback is used only for quality management. Do not enter passport, payment or other sensitive information.',submit:'Submit feedback',sending:'Submitting…',successTitle:'Thank you for your feedback',successText:'Your response has been submitted successfully. We hope to welcome you to China again.',again:'Submit another response',required:'This field is required',ratingRequired:'Please select a rating',consentRequired:'Please confirm your consent',network:'Submission failed. Please check your connection and try again.',hotelBreakfast:'Hotel breakfast',hotelFacilities:'Hotel facilities',hotelService:'Hotel service',restaurantQuality:'Restaurant food quality',restaurantService:'Restaurant service',guideAttitude:'Guide service attitude',overall:'Overall satisfaction'},
ru:{back:'← Язык',eyebrow:'ВАШЕ ПУТЕШЕСТВИЕ — НАША ЗАБОТА',title:'Оценка путешествия по Китаю',intro:'Благодарим за путешествие с Nimbus Travel. Ваш отзыв помогает нам улучшать качество каждой поездки по Китаю.',trip:'Информация о поездке',tripHelp:'Укажите код группы и маршрут вашей поездки.',group:'Код группы',name:'Имя и фамилия',cities:'Посещённые города',itinerary:'Маршрут',spots:'Основные достопримечательности',service:'Оценка услуг',ratingHelp:'Выберите от одной до пяти звёзд. Пять звёзд означает отлично.',commentsTitle:'Комментарии и предложения',commentsHelp:'Расскажите о лучших моментах поездки и о том, что можно улучшить.',consent:'Я согласен(на), что Nimbus Travel может использовать отзыв для повышения качества услуг.',privacy:'Отзыв используется только для контроля качества. Не указывайте паспортные, платёжные и другие конфиденциальные данные.',submit:'Отправить отзыв',sending:'Отправка…',successTitle:'Спасибо за ваш отзыв',successText:'Ваш отзыв успешно отправлен. Желаем приятного путешествия и будем рады новой встрече.',again:'Отправить ещё один отзыв',required:'Заполните это поле',ratingRequired:'Выберите оценку',consentRequired:'Подтвердите согласие',network:'Не удалось отправить отзыв. Проверьте интернет и повторите попытку.',hotelBreakfast:'Завтрак в отеле',hotelFacilities:'Оснащение отеля',hotelService:'Обслуживание в отеле',restaurantQuality:'Качество блюд',restaurantService:'Обслуживание в ресторане',guideAttitude:'Работа и отношение гида',overall:'Общая удовлетворённость'},
es:{back:'← Idioma',eyebrow:'SU VIAJE, NUESTRO CUIDADO',title:'Encuesta de satisfacción del viaje a China',intro:'Gracias por viajar con Nimbus Travel. Sus comentarios nos ayudan a mejorar cada viaje en China.',trip:'Información del viaje',tripHelp:'Indique el grupo y el itinerario en el que participó.',group:'Código del grupo',name:'Nombre',cities:'Ciudades visitadas',itinerary:'Itinerario',spots:'Principales lugares turísticos',service:'Valoración del servicio',ratingHelp:'Seleccione de una a cinco estrellas. Cinco significa excelente.',commentsTitle:'Comentarios y sugerencias',commentsHelp:'Comparta los mejores momentos, sus sugerencias o aquello que podamos mejorar.',consent:'Acepto que Nimbus Travel utilice estos comentarios para mejorar la calidad del servicio.',privacy:'Los comentarios se utilizan solamente para la gestión de calidad. No incluya datos de pasaporte, pago ni otra información sensible.',submit:'Enviar evaluación',sending:'Enviando…',successTitle:'Gracias por sus comentarios',successText:'Su evaluación se ha enviado correctamente. Esperamos darle la bienvenida de nuevo.',again:'Enviar otra respuesta',required:'Este campo es obligatorio',ratingRequired:'Seleccione una valoración',consentRequired:'Confirme su consentimiento',network:'No se pudo enviar. Compruebe la conexión e inténtelo de nuevo.',hotelBreakfast:'Desayuno del hotel',hotelFacilities:'Instalaciones del hotel',hotelService:'Servicio del hotel',restaurantQuality:'Calidad de la comida',restaurantService:'Servicio del restaurante',guideAttitude:'Actitud y servicio del guía',overall:'Satisfacción general'}
};
const ratingFields=[['hotelDesayuno','hotelBreakfast'],['hotelInstalacion','hotelFacilities'],['hotelServicio','hotelService'],['restCalidad','restaurantQuality'],['restServicio','restaurantService'],['guiaActitud','guideAttitude'],['satisfaccionGeneral','overall']];
let language='en';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function uuid(){return crypto.randomUUID?crypto.randomUUID():'fb-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function setLanguage(lang){language=TEXT[lang]?lang:'en';document.documentElement.lang=language;$$('[data-t]').forEach(el=>{const key=el.dataset.t;if(TEXT[language][key])el.textContent=TEXT[language][key]});$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===language));renderRatings();}
function renderRatings(){const old={};ratingFields.forEach(([name])=>{old[name]=$(`[name="${name}"]`)?.value||''});$('#ratings').innerHTML=ratingFields.map(([name,key])=>`<div class="rating-row"><div class="rating-name">${TEXT[language][key]}<small>1 · 2 · 3 · 4 · 5</small></div><div><input type="hidden" name="${name}" value="${old[name]||''}"><div class="stars" data-rating="${name}">${[1,2,3,4,5].map(n=>`<button type="button" class="star ${Number(old[name])>=n?'selected':''}" data-value="${n}" aria-label="${n} stars">★</button>`).join('')}</div><p class="error" data-error="${name}"></p></div></div>`).join('');$$('.stars').forEach(box=>box.addEventListener('click',e=>{const b=e.target.closest('.star');if(!b)return;const v=Number(b.dataset.value);box.previousElementSibling.value=v;[...box.children].forEach(x=>x.classList.toggle('selected',Number(x.dataset.value)<=v));box.parentElement.querySelector('.error').textContent=''}));}
function openForm(lang){setLanguage(lang);$('#landing').classList.add('hidden');$('#formPage').classList.remove('hidden');window.scrollTo(0,0)}
function showLanding(){$('#formPage').classList.add('hidden');$('#landing').classList.remove('hidden');window.scrollTo(0,0)}
$$('[data-open-lang]').forEach(b=>b.addEventListener('click',()=>openForm(b.dataset.openLang)));$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));$('#backButton').addEventListener('click',showLanding);
$('#comments').addEventListener('input',e=>$('#count').textContent=e.target.value.length);$('#year').textContent=new Date().getFullYear();
function clearErrors(){$$('.error').forEach(x=>x.textContent='');$('#message').className='message';$('#message').textContent=''}
function validate(){clearErrors();let ok=true;['groupCode','name','ciudades','itinerario'].forEach(name=>{const el=$(`[name="${name}"]`);if(!el.value.trim()){$(`[data-error="${name}"]`).textContent=TEXT[language].required;ok=false}});ratingFields.forEach(([name])=>{if(!$(`[name="${name}"]`).value){$(`[data-error="${name}"]`).textContent=TEXT[language].ratingRequired;ok=false}});if(!$('#consent').checked){$('[data-error="consent"]').textContent=TEXT[language].consentRequired;ok=false}return ok}
$('#surveyForm').addEventListener('submit',async e=>{e.preventDefault();if(!validate())return;const btn=$('#submitButton');btn.disabled=true;btn.textContent=TEXT[language].sending;const data=Object.fromEntries(new FormData(e.currentTarget).entries());if(data.website){btn.disabled=false;btn.textContent=TEXT[language].submit;return}delete data.website;Object.assign(data,{submissionId:uuid(),submittedAt:new Date().toISOString(),language,formVersion:CONFIG.formVersion,sourceUrl:location.href});try{const res=await fetch(CONFIG.endpoint,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)});const text=await res.text();let result={};try{result=JSON.parse(text)}catch{result={ok:res.ok&&text.trim().toLowerCase()==='ok'}}if(!res.ok||result.ok===false)throw new Error(result.message||'submit failed');localStorage.setItem('nimbus-last-submission',JSON.stringify({id:data.submissionId,at:data.submittedAt}));$('#surveyForm').classList.add('hidden');$('#success').classList.add('show');window.scrollTo({top:0,behavior:'smooth'})}catch(err){const msg=$('#message');msg.textContent=TEXT[language].network;msg.className='message show bad'}finally{btn.disabled=false;btn.textContent=TEXT[language].submit}});
$('#again').addEventListener('click',()=>{$('#surveyForm').reset();$('#count').textContent='0';renderRatings();$('#success').classList.remove('show');$('#surveyForm').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})});
